# -*- coding: utf-8 -*-
from .common import common
from .br import br
from .ca import ca
from .cnh import cnh
from .cv import cv
from .cy import cy
from .de import de
from .en import en
from .es import es
from .et import et
from .eu import eu
from .eo import eo
from .fa import fa
from .fr import fr
from .gaIE import gaIE
from .it import it
from .kab import kab
from .ky import ky
from .nl import nl
from .sl import sl
from .tr import tr
from .tt import tt
from .zhTW import zhTW
